ALTER TABLE reviews DROP INDEX IF EXISTS UK_USER_PRODUCT;

ALTER TABLE reviews ADD CONSTRAINT UK_USER_PRODUCT_ORDER UNIQUE (user_id, product_id, order_id);

ALTER TABLE reviews MODIFY order_id BIGINT NOT NULL;
