spring.datasource.url=jdbc:mariadb://${MARIADB_HOST:mariadb}:${MARIADB_PORT:3306}/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MARIADB_USER:root}
spring.datasource.password=${MARIADB_PASSWORD:}
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
jwt.secret=${JWT_SECRET:MySecretKeyForJWTTokenGeneration2026MicroserviceDemo2VeryLong}
jwt.reset-password-expiration=900000
jwt.reset-password-url=http://localhost:3001/reset-password
