spring.data.mongodb.uri=mongodb://${MONGODB_HOST:mongodb}:${MONGODB_PORT:27017}/order_db
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
jwt.secret=${JWT_SECRET:MySecretKeyForJWTTokenGeneration2026MicroserviceDemo2VeryLong}
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
