spring.datasource.url=jdbc:mariadb://${MARIADB_HOST:mariadb}:${MARIADB_PORT:3306}/payment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MARIADB_USER:root}
spring.datasource.password=${MARIADB_PASSWORD:}
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
