spring.application.name=Payment-service
server.port=8090
spring.datasource.url=jdbc:mariadb://localhost:3306/payment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

vnpay.tmn-code=M9XLW4DH
vnpay.hash-secret=8TM087422A4KW07CVGE2V0K0Z0Z0XO5O
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:3001/vnpay-return
